# Generated by Django 4.2.5 on 2023-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
