# Generated by Django 4.2.5 on 2023-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useraccount_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
